name: Publish OCI resource
description: Publish OCI image as a charm resource
inputs:
  charm-name:
    required: true
    description: Name of the charm to which the resource will be linked
  resource-name:
    required: true
    description: Name of the resource
  charmhub-token:
    required: true
    description: Charmhub access token
 outputs:
  revision: ${{ steps.publish.outputs.revision }}
runs:
  using: composite
  steps:
    - name: Install charmcraft
      shell: bash
      run: sudo snap install charmcraft --classic
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.resource-name }}
        path: /tmp
    - name: Publish image
      id: publish
      env:
        CHARMCRAFT_AUTH: ${{ inputs.charmhub-token }}
      shell: bash
      run: |
        imageId=$(docker load --input /tmp/${{ inputs.resource-name }}.tar | sed -e "s/^Loaded image ID: //")
        out=$(charmcraft upload-resource ${{ inputs.charm-name }} ${{ inputs.resource-name }} --image=$imageId --verbosity=trace)
        revision=$(echo $out | awk '{ print $16 }')
        echo "::set-output name=revision::$revision"
        