name: Publish OCI resource
description: Publish OCI image as a charm resource
inputs:
  dockerfile:
    required: true
    description: Dockerfile filename
  charm-name:
    required: true
    description: Name of the charm to which the resource will be linked
  resource-name:
    required: true
    description: Name of the resource
  charmhub-token:
    required: true
    description: Charmhub access token
runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install charmcraft
      run: sudo snap install charmcraft --classic
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx
    - name: Build image
      id: build_image
      uses: docker/build-push-action@v2
      with:
        file: ${{ inputs.charm-name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        outputs: type=oci,dest=/tmp/myimage.tar
    - name: Publish image
      env:
        CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
      run: |
        docker load --input /tmp/myimage.tar
        charmcraft upload-resource ${{ inputs.charm-name }} ${{ inputs.resource-name }} --image=${{ steps.build_image.outputs.imageid }}