name: Publish OCI resource
description: Publish OCI image as a charm resource
inputs:
  dockerfile:
    required: true
    description: Dockerfile filename
  charm-name:
    required: true
    description: Name of the charm to which the resource will be linked
  resource-name:
    required: true
    description: Name of the resource
  charmhub-token:
    required: true
    description: Charmhub access token
runs:
  using: composite
  steps:
    - uses: ./.github/actions/build_oci_image.yaml
      id: build-image
      with:
        dockerfile: ${{ inputs.dockerfile }}
        resource-name: ${{ inputs.resource-name }}
    - name: Publish image
      env:
        CHARMCRAFT_AUTH: ${{ secrets.charmhub-token }}
      run: |
        docker load --input /tmp/${{ inputs.resource-name }}.tar
        charmcraft upload-resource ${{ inputs.charm-name }} ${{ inputs.resource-name }} --image=${{ jobs.build-image.outputs.image-id }}