{
 "title": "Indico Operator",
 "description": "Dashboard for the Indico Operator, powered by Juju.",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGINX Status for $juju_unit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "repeat": "juju_unit",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nginx_up{}" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{}[5m])",
     "legendFormat": "{{juju_unit}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{}[5m])",
     "legendFormat": "{{juju_unit}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    { "expr": "nginx_connections_active{}", "legendFormat": "{{juju_unit}} active" },
    { "expr": "nginx_connections_reading{}", "legendFormat": "{{juju_unit}} reading" },
    { "expr": "nginx_connections_waiting{}", "legendFormat": "{{juju_unit}} waiting" },
    { "expr": "nginx_connections_writing{}", "legendFormat": "{{juju_unit}} writing" }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{}[5m])",
     "legendFormat": "{{juju_unit}} total requests"
    }
   ]
  }
 ]
}