{
 "title": "Indico Service Health",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "LATENCY",
   "type": "text",
   "description": "No metric available for getting latency.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "content": "Not available." },
   "targets": [
    { "expr": "nginx_connections_handled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "description": "NGINX Downtime Events",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "(1 - nginx_up)", "legendFormat": "{{juju_model}} {{juju_unit}}" }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "description": "NGINX Request Traffic (requests/min)",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total[5m])) / 5",
     "legendFormat": "requests/min"
    }
   ]
  },
  {
   "title": "SATURATION",
   "type": "timeseries",
   "description": "CPU usage of the most resource-consuming unit over the last 5 minutes",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{juju_unit=~\"indico.*\"}[2m]))",
     "legendFormat": "CPU usage"
    }
   ]
  }
 ]
}