name: Comment on PR
description: Publish a comment on a PR and remove previous bot comments
inputs:
  artifact-name:
    required: true
    description: Artifact containing a JSON like list of comments to be published
  github-token:
    required: true
    description: Github token
runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.resource-name }}
    - name: Comment on PR
      uses: actions/github-script@v6.2.0
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const script = require('${{ github.workspace }}/.github/actions/comment_pr/dist/comment_pr.js')
          await script({github, context})
