name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  comment-on-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/comment_pr
        with:
          artifact-name: report
          github-token: ${{ secrets.GITHUB_TOKEN }}
