name: Upload Charm Docs

on: [push, pull_request]

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish documentation
        uses: canonical/upload-charm-docs@feature/migration
        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
      - name: Show index page
        run: echo '${{ steps.publishDocumentation.outputs.index_url }}'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
