# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: Get Indico version

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        description: The working directory for jobs
        default: "./"
    outputs:
      version:
        description: Indico version
        value: ${{ jobs.get-indico-version.outputs.version }}

jobs:
  get-indico-version:
    name: Get Indico version
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ env.INDICO_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Get version from rockfile
        run: |
          version=$(grep -oP '[^[:space:]]*indico==[^[:space:]]*' indico_rock/rockcraft.yaml | awk -F '==' '{print $2}')
          echo "INDICO_VERSION=$version" >> $GITHUB_ENV
