name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-tests:
    uses: 
      canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      juju-channel: 3.6/stable
      channel: 1.35-strict/stable
      modules: '["test_charm.py", "test_s3.py", "test_saml.py", "test_smtp.py"]'
      trivy-exit-code: 0
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
