name: Integration tests (require secrets)

on:
  pull_request:

jobs:
  integration-test-with-secrets:
    runs-on: ubuntu-latest
    name: Integration Tests (require secrets)
    steps:
      - uses: actions/checkout@v3

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s

      - name: Enable microk8s plugins
        run: |
          sudo microk8s enable hostpath-storage ingress registry
          sudo microk8s kubectl -n kube-system rollout status -w deployment/hostpath-provisioner
          sudo microk8s kubectl -n ingress rollout status -w daemonset.apps/nginx-ingress-microk8s-controller
          sudo microk8s kubectl -n container-registry rollout status -w deployment/registry

      - name: Install tox
        run: python3 -m pip install tox

      - name: Install rockcraft
        run: sudo snap install --edge rockcraft --classic

      - name: Config iptables
        run: |
          sudo iptables -I DOCKER-USER  -j ACCEPT
      - name: Build indico rock
        working-directory: ./indico_rock
        run: |
          rockcraft
          skopeo --insecure-policy copy oci-archive:indico_1.0_amd64.rock docker-daemon:localhost:32000/indico:test
          docker push localhost:32000/indico:test

      - name: Build indico-nginx rock
        working-directory: ./nginx_rock
        run: |
          rockcraft
          skopeo --insecure-policy copy oci-archive:indico-nginx_1.0_amd64.rock docker-daemon:localhost:32000/indico-nginx:test
          docker push localhost:32000/indico-nginx:test

      - name: Run integration tests
        run: |
          tox -e integration -- \
          -m requires_secrets \
          --saml-email ${{ secrets.TEST_SAML_EMAIL }} \
          --saml-password ${{ secrets.TEST_SAML_PASSWORD }} \
          --indico-nginx-image=localhost:32000/indico-nginx:test \
          --indico-image=localhost:32000/indico:test
