name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@add-support-for-running-script-before-integration-tests
    secrets: inherit
