name: ghcr Integration tests

on:
  workflow_dispatch:
  push:
    branches:
      - "ISD-192-test-git-hubs-container-registry-performance-for-existing-workflows"

env:
  REGISTRY: ghcr.io
  OWNER: canonical
  INDICO_IMAGE_NAME: indico
  NGINX_INDICO_IMAGE_NAME: indico-nginx


jobs:
  build-indico-image:
    name: Build indico image
    runs-on: ubuntu-20.04
    outputs:
      image-id: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.INDICO_IMAGE_NAME }}

      - name: Build and push indico image
        id: build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: indico.Dockerfile
  build-indico-nginx-image:
    name: Build nginx image
    runs-on: ubuntu-20.04
    outputs:
      image-id: ${{ steps.build.outputs.imageid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.NGINX_INDICO_IMAGE_NAME }}

      - name: Build and push nginx indico image
        id: build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: indico-nginx.Dockerfile

  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-20.04
    needs: [build-indico-image, build-indico-nginx-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Configure GHCR in microk8s
        run: |
          sudo chmod 755 /var/snap/microk8s/current/args/containerd-template.toml && sudo echo "
          [plugins.\"io.containerd.grpc.v1.cri\".registry.configs.\"ghcr.io\".auth]
          username = \"${{ github.actor }}\"
          password = \"${{ secrets.GITHUB_TOKEN }}\"
          " >> /var/snap/microk8s/current/args/containerd-template.toml
      - name: Run integration tests
        run: tox -e integration -- --model testing --indico-image ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.INDICO_IMAGE_NAME }}:isd-192-test-git-hubs-container-registry-performance-for-existing-workflows --indico-nginx-image ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.NGINX_INDICO_IMAGE_NAME }}:isd-192-test-git-hubs-container-registry-performance-for-existing-workflows
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          app: indico
          model: testing
