name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  load-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@load-tests
    with:
      load-test-enabled: true
    secrets: inherit