name: Load tests

on:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  load-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    with:
      load-test-enabled: true
      load-test-run-args: "-e LOAD_TEST_HOST=localhost"
    secrets: inherit
