name: Test

on:
  pull_request:
jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/ci.yaml
  test-stuff:
    permissions:
      issues: write
      pull-requests: write
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        env:
          URL: ${{ github.event.issue.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $URL
          echo ${{ github.event.issue }}
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "This is a test" }'