name: Release charm to a branch in channel edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/integration_test.yaml
  publish-indico-image:
    name: Publish indico image to charmhub
    runs-on: ubuntu-latest
    needs: [ lib-check, tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish_oci_resource
        with:
          charm-name: indico
          resource-name: indico-image
          charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
  publish-indico-nginx-image:
    name: Publish nginx image to charmhub
    runs-on: ubuntu-latest
    needs: [ lib-check, tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/publish_oci_resource
        with:
          charm-name: indico
          resource-name: indico-nginx-image
          charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
  select-branch:
    name: Select target branch
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.extract-branch.outputs.branch }}
    steps:
      - name: Get target branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-branch
  publish-charm:
    name: Publish charm to latest/edge/${{ needs.select-branch.outputs.branch }}
    runs-on: ubuntu-latest
    needs: [ select-branch, publish-indico-image, publish-indico-nginx-image ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@1.0.3
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: ${{ needs.select-branch.outputs.branch }}
          upload-image: false
