name: Release charm to a branch in channel edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/publish_branch@initial-workflow-templates
    secrets: inherit
