name: Release charm to a branch in channel edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_branch.yaml@v1.0.0
    secrets: inherit
