name: Release charm to a branch in channel edge

on:
  workflow_dispatch:
    secrets:
      CHARMHUB_TOKEN:
        required: true

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_branch.yaml@add-support-for-running-script-before-integration-tests
    secrets: inherit
