name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@reuse-images-from-pr-checks
    secrets: inherit
    with:
      channel: latest/edge
      integration-test-extra-arguments: -m "not (requires_secrets)"
      trivy-image-config: "trivy.yaml"
