# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Test terraform files

on:
  pull_request:
    paths:
      - 'terraform/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate terraform configuration files
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: 'terraform'
    steps:
      - name: Check out code
        uses: actions/checkout@v5.0.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Run terraform fmt
        run: terraform fmt -check -recursive
        working-directory: ${{env.WORKING_DIR}}

      - name: Setup Tflint
        uses: terraform-linters/setup-tflint@v6.2.1
        with:
          tflint_wrapper_enabled: true

      - name: Run tflint
        run: |
          tflint --version
          tflint --init
          tflint -f compact --recursive
        working-directory: ${{env.WORKING_DIR}}

  required_status_checks:
    name: Required Terraform Validate Status Checks
    runs-on: ubuntu-latest
    needs:
      - validate
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - run: |
          [ '${{ needs.validate.result }}' = 'success' ] || (echo validate failed && false)
